services:
  users-springboot:
    build:
      context: ./users-springboot
    ports:
      - 8080:8080

  frontend-react:
    build:
      context: ./frontend-react
    ports:
      - 3000:3000

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
